###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: docker-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=dbrootpw
      - MYSQL_DATABASE=phonebook
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpw
    ports:
      - 127.0.0.1:3307:3306 # Connect to it via -h127.0.0.1 --port=3307

  webserver:
    image: nginx:alpine
    container_name: docker-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: docker-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
